trigger: none

pool:
  name: Default
  demands:
    - Agent.Name -equals aws-ec2-agent-01

steps:
  - checkout: self

  - script: |
      echo "===== Agent ====="
      whoami
      hostname

      echo "===== Azure CLI ====="
      az --version

      echo "===== ACR Build ====="
      az acr build \
        --registry acrmlopsdev925714 \
        --image mlflow-server:1.0.0 \
        --file services/mlflow-server/Dockerfile \
        .
    displayName: "Build and Push MLflow Image to ACR"