trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  imageRepository: validation-service
  imageTag: $(Build.BuildId)

steps:

  - checkout: self

  - task: UsePythonVersion@0
    displayName: Use Python 3.12
    inputs:
      versionSpec: "3.12"

  - script: |
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    displayName: Install Python dependencies

  - script: |
      python -m pytest validation/tests tests/data/test_validation.py -v
    displayName: Run validation tests

  - task: Docker@2
    displayName: Build validation Docker image
    inputs:
      command: build
      Dockerfile: validation/Dockerfile
      buildContext: .
      repository: $(imageRepository)
      tags: |
        $(imageTag)
        latest

  - script: |
      echo "Saving Docker image as pipeline artifact..."

      docker save $(imageRepository):$(imageTag) | gzip > $(Build.ArtifactStagingDirectory)/validation-service-$(imageTag).tar.gz

      echo "Docker image saved successfully."
      ls -lh $(Build.ArtifactStagingDirectory)/validation-service-$(imageTag).tar.gz
    displayName: Save Docker image

  - task: PublishPipelineArtifact@1
    displayName: Publish validation Docker image artifact
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)/validation-service-$(imageTag).tar.gz"
      artifact: validation-docker-image
      publishLocation: pipeline