apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlops-keyvault
  namespace: mlops

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"
    clientID: "282f32ba-59a5-4277-963c-ae6c54d667f7"
    keyvaultName: "kvmlopsdev925714"
    tenantId: "3af607b5-8076-4124-9033-cb8dc0c4ff37"

    objects: |
      array:
        - |
          objectName: workload-identity-test
          objectType: secret
          objectVersion: ""

  secretObjects:
    - secretName: mlops-keyvault-secret
      type: Opaque
      data:
        - objectName: workload-identity-test
          key: workload-identity-test