apiVersion: v1
kind: Namespace
metadata:
  name: mlops

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlops-workload
  namespace: mlops
  annotations:
    azure.workload.identity/client-id: "282f32ba-59a5-4277-963c-ae6c54d667f7"
